// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.GameDTO", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameID"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("GameID");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            AltText = "Long number memory icon",
                            Description = "Memorize as many digits of a long number as possible.",
                            Icon = "src/assets/longNumberIcon.svg",
                            Route = "/longNumber",
                            Title = "Long number memory"
                        },
                        new
                        {
                            GameID = 2,
                            AltText = "Chimp test icon",
                            Description = "Test your memory by remembering the order of numbers displayed on the screen.",
                            Icon = "src/assets/chimpIcon.svg",
                            Route = "/chimpTest",
                            Title = "Chimp Test"
                        },
                        new
                        {
                            GameID = 3,
                            AltText = "Sequence memory icon",
                            Description = "Remember and recall increasingly larger sequence of action showed.",
                            Icon = "src/assets/sequenceIcon.svg",
                            Route = "/sequence",
                            Title = "Sequence Memorization"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
