global using Xunit;
global using Microsoft.EntityFrameworkCore;
global using FluentAssertions;
global using Moq;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.IO;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Microsoft.Extensions.Logging;

global using API.DTOs;
global using API.Data;
global using API.Models;
global using API.Services;
global using API.Controllers;
global using API.Exceptions;
global using API.Interfaces;
